language: node_js
node_js:
- '9'

script:
- yarn test
- yarn run build
- echo "draw.pomle.com" > build/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master
